### ISSUE TITLE
Request for Indonesia

### ISSUE THREAD

**Issue by rraymondhp** [qiskit-community/qiskit-translations#192] opened 2020-08-14 06:33 UTC
### Summary

- The language that I'd like to request: Indonesian (Bahasa Indonesia)
- I'd like to be a **Translation Lead**

**Comment by veenaiyuri** [comment] 2020-08-14 06:43
Hi @rraymondhp  Thank you for showing your support to be a Translation Lead for the Indonesian language. Much appreciated! Actually, there is already an issue opened for Indonesian translations (#183 )

With you joining as translation lead, we shall now be able to officially start supporting Indonesian in Qiskit Docs. 
In the mean time, please add your name in https://github.com/qiskit-community/qiskit-translations/blob/master/LOCALIZATION_CONTRIBUTORS and sign the CLA. Thanks.

I'm closing this issue since it is a duplicate of #183

**Comment by veenaiyuri** [comment] 2020-08-14 06:44
I'm closing this issue since it is a duplicate of #183

**Closed by veenaiyuri** 2020-08-14 06:44 UTC
Labels: New Language Request, duplicate, help wanted
