### ISSUE TITLE
Request for Hindi(HI) Language

### ISSUE THREAD

**Issue by born-2learn** [qiskit-community/qiskit-translations#162] opened 2020-08-07 00:19 UTC
### Summary

- Hindi is the 3rd most spoken language in the world with more than 615 million speakers worldwide, as per [newsonair](http://newsonair.com/News?title=Hindi-is-3rd-most-spoken-language-in-the-world-with-615-million-speakers-after-English%2C-Mandarin&id=381514). It is also the National language of India.
- I'd like to be a _Translator_ for the Hindi Language.
- I understand that to start the process for a new language, we will require at least 3 contributors and proof-readers. We have students willing to volunteer for the same from the [QPower Quantum community](https://www.linkedin.com/company/qpower).

**Comment by SooluThomas** [comment] 2020-08-07 13:40
Hi @born-2learn! Thank you for your interest to contribute. There is already an issue opened for Hindi translations (#4). As [mentioned in the criteria](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#how-to-add-a-new-language-to-translate), we would want a minimum of 3 active volunteers to start a translation. Please use issue #4 to start a discussion and invite more interested volunteers. 

I'm closing this issue since it is a duplicate of #4.

**Closed by SooluThomas** 2020-08-07 13:40 UTC
Labels: duplicate

**Comment by born-2learn** [comment] 2020-08-07 17:17
Sure, I'll continue the discussion in issue #4
