### ISSUE TITLE
Request for [Bengali]

### ISSUE THREAD

**Issue by abhik-99** [qiskit-community/qiskit-translations#197] opened 2020-08-14 16:48 UTC
### Summary

- I'm actually working with a Team of researchers and enthusiasts based out of Kolkata, WB and we would like to translate the Qiskit Documentation to Bengali
- @thecrazyphysicist369 will be  _Translation Lead/ Proofreader/ Translator_ for this endeavour.

We talked with Brian Ingmanson and Yuri Kobayashi. Yuri mentioned that there was another team interested ( #147 ). Currently, we have 6 members in our Team consisting of @mojutijatir (Quantum Computing Research Fellow at ISI, Kolkata), @thecrazyphysicist369 , @JanapriyoJp, @Aniket049, myself and @aishwarya25252. We have created a Github Org [Qiskit-Bangla](https://github.com/Qiskit-Bangla) for the existing team and for others who are fluent in Bengali and have a knack for Quantum Computing and Qiskit to collaborate on. 
**We are open to collaborating with others who are interested to help (#147).** 

Awaiting further instructions. Thank You!

**Comment by SooluThomas** [comment] 2020-08-14 17:36
Hi @abhik-99, There is already an issue #147 open for Bengali. Please use that issue for further discussion.

I'm closing this issue since it is a duplicate of #147.

**Closed by SooluThomas** 2020-08-14 17:36 UTC
Labels: duplicate
