### ISSUE TITLE
Request for [HINDI]

### ISSUE THREAD

**Issue by anupamaray** [qiskit-community/qiskit-translations#169] opened 2020-08-08 10:40 UTC
### Summary

- We want to translate the Qiskit textbook and documentation to Hindi.  (Hindi is the lingua franca for over 500 million people and there is a huge growing interest in Quantum among Indian Students. We observed some students already working on Qiskit but we are aiming for better outreach via India Quantum Challenge, Professor Collaborations and several other mediums.)
- I'd like to be a HINDI_Translation Lead. I am a native Hindi speaker and I am the lead researcher for Watson NLP stack extension to Hindi. I have Quantum theory knowledge and Qiskit understanding. I am taking the Qiskit Advocate test and also lined up for my Quantum Ambassador training in September
 I have a team of people in IBM Research India and some from IBM India (Systems and Quantum Computing COC) with whom we are trying to create the India Ecosystem. There are 4 Q-Ambassadors out of which one will be the proofreader and others will join for translation like me.

**Comment by veenaiyuri** [comment] 2020-08-10 08:12
Thank you for your interest in translating Qiskit into Hindi language. Please edit the following file by adding "Hindi (HI)" as a new heading with your name under it. Then commit changes.  Please make sure to sign the CLA after you have successfully committed changes. Thank you. 
https://github.com/qiskit-community/qiskit-translations/edit/master/LOCALIZATION_CONTRIBUTORS

**Comment by SooluThomas** [comment] 2020-08-10 12:27
Hi @anupamara! Thank you for your interest to contribute. There is already an open issue requesting for Hindi translations (#4). Please use that issue to follow-up with other volunteers who are interested to contribute as well. 

I'm closing this issue since this is a duplicate of #4. Please follow-up in that issue.

**Closed** 2020-08-10 12:28 UTC
Labels: duplicate

**Comment by Yudhishthir97** [comment] 2020-11-19 18:58
I would like to be a part of the Hindi translation project. I'm a native Hindi speaker and am currently working on translating books in other fields also into Hindi.

**Comment by SooluThomas** [comment] 2020-11-20 00:30
@Yudhishthir97, we already have Hindi translations open in Crowdin as labeled in #4. Please open a pull request to add your name to the LOCALIZATION_CONTRIBUTORS file by following the instructions in the [README.md](https://github.com/qiskit-community/qiskit-translations/blob/master/README.md#to-sign-up-to-participate-in-translations).

Thank you for your interest in contributing to Qiskit. Please let me know if anything is unclear. Thank you.
